"""add remaining entities

Revision ID: 564fc4e19487
Revises: c8ee68f1a13f
Create Date: 2026-07-20 05:44:16.398018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '564fc4e19487'
down_revision: Union[str, None] = 'c8ee68f1a13f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('purchase_request', 'write_off_act', 'work_order', name='document_template_type'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('field_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_approver_role', postgresql.ENUM('Admin', 'IT-Head', 'Engineer', 'Executive', 'User', name='user_role', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('system', sa.Enum('zabbix', 'espocrm', 'openproject', 'kaspersky', 'n8n', name='integration_system'), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='integration_direction'), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_integration_log_system_created_at', 'integration_log', ['system', 'created_at'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('purchase_request', 'write_off_act', 'work_order', name='document_template_type', create_type=False), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'executed', 'rejected', name='order_status'), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['document_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_author_id'), 'order', ['author_id'], unique=False)
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_index(op.f('ix_order_type'), 'order', ['type'], unique=False)
    op.create_table('monitoring_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('host_identifier', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ok', 'warning', 'critical', 'unknown', name='monitoring_health_status'), nullable=False),
    sa.Column('last_value', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('zabbix', 'kaspersky', name='monitoring_source'), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_monitoring_status_host_source', 'monitoring_status', ['host_identifier', 'source'], unique=True)
    op.create_table('movement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('from_location', sa.String(length=255), nullable=True),
    sa.Column('to_location', sa.String(length=255), nullable=False),
    sa.Column('initiator_id', sa.UUID(), nullable=False),
    sa.Column('moved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['initiator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movement_asset_id_moved_at', 'movement', ['asset_id', 'moved_at'], unique=False)
    op.create_table('order_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_history_order_id'), 'order_history', ['order_id'], unique=False)
    op.create_table('repair',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('repair_type', sa.String(length=150), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('executor', sa.String(length=255), nullable=True),
    sa.Column('executor_espocrm_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'done', 'cancelled', name='repair_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_repair_asset_id_status', 'repair', ['asset_id', 'status'], unique=False)
    op.create_table('ticket',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='ticket_priority'), nullable=False),
    sa.Column('status', sa.Enum('new', 'in_progress', 'done', 'rejected', name='ticket_status'), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('web', 'max', 'zabbix_auto', name='ticket_source'), nullable=False),
    sa.Column('external_op_id', sa.String(length=64), nullable=True),
    sa.Column('external_espo_id', sa.String(length=64), nullable=True),
    sa.Column('merged_into_ticket_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['merged_into_ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_assignee_id'), 'ticket', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_ticket_external_op_id'), 'ticket', ['external_op_id'], unique=False)
    op.create_index('ix_ticket_status_priority', 'ticket', ['status', 'priority'], unique=False)
    op.create_table('attachment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_ticket_id'), 'attachment', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachment_ticket_id'), table_name='attachment')
    op.drop_table('attachment')
    op.drop_index('ix_ticket_status_priority', table_name='ticket')
    op.drop_index(op.f('ix_ticket_external_op_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_assignee_id'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_index('ix_repair_asset_id_status', table_name='repair')
    op.drop_table('repair')
    op.drop_index(op.f('ix_order_history_order_id'), table_name='order_history')
    op.drop_table('order_history')
    op.drop_index('ix_movement_asset_id_moved_at', table_name='movement')
    op.drop_table('movement')
    op.drop_index('ux_monitoring_status_host_source', table_name='monitoring_status')
    op.drop_table('monitoring_status')
    op.drop_index(op.f('ix_order_type'), table_name='order')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_author_id'), table_name='order')
    op.drop_table('order')
    op.drop_table('audit_log')
    op.drop_index('ix_integration_log_system_created_at', table_name='integration_log')
    op.drop_table('integration_log')
    op.drop_table('document_template')

    # Явное удаление enum-типов Postgres — op.drop_table() их не удаляет
    # (см. известную проблему из B01). user_role сюда не входит — он создан
    # в предыдущей миграции (c8ee68f1a13f) и принадлежит ей.
    bind = op.get_bind()
    sa.Enum(name='ticket_source').drop(bind, checkfirst=True)
    sa.Enum(name='ticket_status').drop(bind, checkfirst=True)
    sa.Enum(name='ticket_priority').drop(bind, checkfirst=True)
    sa.Enum(name='repair_status').drop(bind, checkfirst=True)
    sa.Enum(name='monitoring_source').drop(bind, checkfirst=True)
    sa.Enum(name='monitoring_health_status').drop(bind, checkfirst=True)
    sa.Enum(name='order_status').drop(bind, checkfirst=True)
    sa.Enum(name='integration_direction').drop(bind, checkfirst=True)
    sa.Enum(name='integration_system').drop(bind, checkfirst=True)
    sa.Enum(name='document_template_type').drop(bind, checkfirst=True)
    # ### end Alembic commands ###
