"""initial models

Revision ID: c8ee68f1a13f
Revises: 
Create Date: 2026-07-20 00:09:14.475137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8ee68f1a13f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('equipment_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.String(length=150), nullable=True),
    sa.Column('role', sa.Enum('Admin', 'IT-Head', 'Engineer', 'Executive', 'User', name='user_role'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('espocrm_contact_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    comment='Пользователи системы (сотрудники учреждения)'
    )
    op.create_index(op.f('ix_user_department_id'), 'user', ['department_id'], unique=False)
    op.create_index(op.f('ix_user_login'), 'user', ['login'], unique=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_table('asset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_number', sa.String(length=50), nullable=False),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=150), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('in_use', 'repair', 'written_off', 'in_stock', name='asset_status'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('responsible_user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['equipment_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_inventory_number'), 'asset', ['inventory_number'], unique=True)
    op.create_index(op.f('ix_asset_ip_address'), 'asset', ['ip_address'], unique=False)
    op.create_index(op.f('ix_asset_location'), 'asset', ['location'], unique=False)
    op.create_index(op.f('ix_asset_status'), 'asset', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_status'), table_name='asset')
    op.drop_index(op.f('ix_asset_location'), table_name='asset')
    op.drop_index(op.f('ix_asset_ip_address'), table_name='asset')
    op.drop_index(op.f('ix_asset_inventory_number'), table_name='asset')
    op.drop_table('asset')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_login'), table_name='user')
    op.drop_index(op.f('ix_user_department_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('equipment_type')
    op.drop_table('department')
    # ### end Alembic commands ###
    # Явное удаление enum-типов — Alembic autogenerate их не отслеживает,
    # а drop_table не удаляет сам ENUM-тип в PostgreSQL (это отдельный объект схемы)
    sa.Enum(name='asset_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=True)
